# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- project1_dev

pool: default

steps:
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    orchestratorConnection: 'UiPath Dev'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@3
  inputs:
    orchestratorConnection: 'UiPath Dev'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Test'